### ISSUE TITLE
Add picture showing effects chain, and path audio takes

### ISSUE THREAD

**Issue by mungewell** [ELynx/zoom-fx-modding#5]
I understand that you are patching (with IPS) an standard effect to make two new custom ones - RTFM and RainSel.

I am not quite understanding how these new effects are added into the effects chain (ie in a patch) and how the audio from the input(s) flows through them and other effects.

Could you please put this into a picture/flow diagram to explain?

Thanks.

**Comment by ELynx** [comment]
Hi! I am getting back on track with development, and documenting is a good way to start.

To first question, they are added pretty easily, as all other effects. Once in firmware, they can be selected among FX list by scrolling to them.

IPS creates a modded file, then you need custom firmware maker to add FX to it.

To second question, I will document RainSel, and document how I see RTFM better.

**Comment by DutchGuitarDude** [comment]
Hello Elynx,

are you still actively working ont his project?
I would like to discuss some things in private if you do.

**Comment by ELynx** [comment]
@DutchGuitarDude Shure, I do.

Got back to active development couple of days, doing closed beta on stereo processing, with some success. To speed things up, drop me an e-mail to `eduardanonimov@gmail.com`.

**Comment by DutchGuitarDude** [comment]
Hi Eduard,

I was working and testing on midi with the zoom. It works, I can control
the zoom with my boss ms3. PC changes only, but that's all I need.

1 problem though, the zoom only works on midi channel 1, would it possible
to change the midi channel it responds to?

Eric

Op ma 11 jul. 2022 15:57 schreef Eduard ***@***.***>:

**Comment by DutchGuitarDude** [comment]
Sorry I dont have a clue how Github works...What did you achieve?

Op ma 25 jul. 2022 om 23:23 schreef Eduard ***@***.***>:

**Comment by ELynx** [comment]
OK, original issue was about `Add picture showing effects chain, and path audio takes`. So when I close it I mean "I done all I can for the issue, that is I added as much as I can explain about effects chain". Media does not really fit well into github size limit, plus I have no meaningful samples any way, just drones and buzzes I use to test.

Thus this issue in particular is closed because I made as much picrtures as I can. I may add another one, but I cannot just take images from Zoom and plaster them on internet, so I will think if I can make meaningful FX diagram without stepping in pile of copyright.

For diagrams here are:
https://github.com/ELynx/zoom-fx-modding/blob/main/howto/Div0.en.md
https://github.com/ELynx/zoom-fx-modding/blob/main/howto/RTFM.en.md

For our Midi discussion, it was a hijack of the topic. I think I answered as much as I can in my e-mail. But if you want to, for history and "TODO" reason, you can open your own issue, and I will keep it open until either I definitely know I cannot do it, or it is somehow done.

**Comment by ELynx** [comment]
Here, just did that for you.

As of achieving, I am about to release my original plan, independent processing of Left and Right. Going through final tests and documentation.

**Comment by DutchGuitarDude** [comment]
Awesome, thanks!

Op di 26 jul. 2022 14:59 schreef Eduard ***@***.***>:

**Comment by DutchGuitarDude** [comment]
I am very interested in seperate left and right effects too . Is firmware writing on the zoom an easy process?

**Comment by ELynx** [comment]
Not really. I did it a lot of times during development, after you get the hand of it most of the time is spent waiting for process to complete.

I have a step-by-step guide here
https://github.com/ELynx/zoom-fx-modding/blob/main/howto/README.en.md

As usual, do not do night before the gig.

I also have a process to "compress" effects, e.g. default CDR ones shrink to around 80, instead of almost full, but I want to coordinate this with author of Zoom Effect Manager, to save time and work to users.

For actual release of versions that work, files that are needed for release are coming soon, around today if nothing happens.
